EFFECT_TO_VALUE = {
    '-1': 'negative',
    '-0.1': 'minimal_negative',
    '0': 'neutral',
    '0.1': 'minimal_positive',
    '1': 'positive',
    '1 | -1': 'both',
    '?': 'unknown',
    '-3': 'negative',
}

field_name_to_index = [
    'Source_UniProtAC',
    'Source_GeneName',
    'InteractionType',
    'Edge_type',
    'Target_UniProtAC',
    'Target_GeneName',
    'Directness',
    'Effect_ALL',
    'Effect_FINAL',
    'Sources',
    'References',
    'Comment',
    'DataSource',
    'EntryType',
    'Biol_Process',
    'Score',
    'Curator_Name',
    'Reviewed',
    'Personal_Comment',
    'Int_Abrev',
    '#FULL',
    '#MEDIUM',
    '#SMALL',
    '#SIG',
]
